main:
  push:
    - runner:
        cpus: 1
      stages:
        - name: publish
          image: docker:latest
          script: 
            - docker login -u linyuansup -p lty4711177
            - docker build -t linyuansup/opchat:$CODING_BRANCH_SHA .
            - docker push linyuansup/opchat:$CODING_BRANCH_SHA