main:
  push:
    - env:
        CODING_CPUS: 1
    - services:
        - docker
      docker:
        image: alpine
      stages:
        - name: docker info
          script:
            - docker info
            - docker ps