main:
  push:
    - runner:
        cpus: 1
      services:
        - docker
      stages:
        - name: pull on server
          image: appleboy/drone-ssh
          settings:
            host:
              - 43.143.59.198
            username: root
            password: zhangyinqi114514!
            port: 22
            command_timeout: 2m
            script:
              - docker stop opChat
              - docker rm opChat
              - docker image prune
              - docker run -p 80:80 linyuansup/opchat:$CODING_BRANCH_SHA