main:
  push:
    - runner:
        cpus: 1
      stages:
        - name: publish
          image: docker:latest
          script: 
            - systemctl start docker.service
            - docker login -u linyuansup -p lty4711177
            - docker build --pull --rm -f "Dockerfile" -t linyuansup/opchat:$CODING_BRANCH_SHA "."
            - docker push linyuansup/opchat:$CODING_BRANCH_SHA