main:
  push:
    - runner:
        cpus: 1
      service:
        - docker
      stages:
        - name: publish
          script: 
            - echo building......
            - docker build -t linyuansup/opchat:$CODING_BRANCH_SHA .
            - echo login......
            - docker login -u linyuansup -p lty4711177
            - echo pushing......
            - docker push linyuansup/opchat:$CODING_BRANCH_SHA